#通用配置文件
mail:
  server:
    username: cdistc@163.com
    password: xxxx
    debug: true
    auth: true
    protocol: smtp
    server: smtp.163.com
  client:
    sender: cdistc@163.com


mysql:
  schema: pdc
